[window]
opacity = 0.96

[font]
size = 10.0

[font.normal]
family = "Source Code Pro"

[colors.primary]
background = "#282C34"
foreground = "#DCDFE4"

[colors.normal]
black = "#282C34"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#919BAA"

[colors.bright]
black = "#474E5D"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#DCDFE4"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Return", mods = "Control",                      action = "CreateNewWindow" },
  { key = 5,        mods = "Shift",   mode = "Vi|~Search", action = "Last"            },
  { key = 6,        mods = "Shift",   mode = "Vi|~Search", action = "Bracket"         },
  { key = 53,       mods = "Shift",   mode = "Vi|~Search", action = "SearchBackward"  },
]
