[terminal]
shell = { program = "/bin/sh", args = ["-c", "zellij attach default || zellij --new-session-with-layout todo --session default"] }

[window]
opacity = 0.96

[font]
size = 10.0

[font.normal]
family = "Source Code Pro"

[colors.primary]
background = "#2C323C"
foreground = "#ABB2BF"

[colors.normal]
black = "#2C323C"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#919BAA"

[colors.bright]
black = "#5C6370"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#ABB2BF"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "X", mods = "Control|Shift", action = "Copy" },
]
