# Rules
select = ["ALL"]
ignore = [
  "D100",  # Missing docstring in public module
  "D104",  # Missing docstring in public package
  "INP",   # Missing __init__.py for package
]
line-length = 120

[per-file-ignores]
"utilities/ffmeta.py" = ["T20"]  # flake8-print

[pydocstyle]
convention = "google"

[flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "single"
