#!/usr/bin/env fish
set history_count "$(dunstctl count history)"
set displayed_count "$(dunstctl count displayed)"
set waiting_count "$(dunstctl count waiting)"
if test -n "$history_count" -a -n "$displayed_count" -a -n "$waiting_count"
    set total_count (math --scale 0 "$history_count + $displayed_count + $waiting_count")
    if test "$total_count" -ge 1
        printf '%s\n%s' '🔔' "$total_count"
    end
end
