#!/bin/bash

set -e
set -u
set -o pipefail

echo -n "Play '${nnn}' with MPV. Shuffle (y/N)? "
read -r shuffle

if [[ -d "${nnn}" ]]; then
  if [[ "${shuffle}" == [yY] ]]; then
    find "${nnn}" -maxdepth 2 -type f -not -path '*/.*' \
      '(' -iname '*.mp3' -or -iname '*.m4a' -or -iname '*.ogg' -or -iname '*.opus' -or -iname '*.flac' ')' \
      -exec mpv --profile=music --shuffle --loop-playlist '{}' '+' &
  else
    find "${nnn}" -maxdepth 2 -type f -not -path '*/.*' \
      '(' -iname '*.mp3' -or -iname '*.m4a' -or -iname '*.ogg' -or -iname '*.opus' -or -iname '*.flac' ')' \
      -print0 \
        | sort -nz \
        | xargs -0 mpv --profile=music &
  fi
else
  if [[ "${shuffle}" == [yY] ]]; then
    mpv --profile=music --shuffle --loop-playlist "${nnn}" &
  else
    mpv --profile=music "${nnn}" &
  fi
fi
