[package]
name = "openweather"
version = "1.0.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking"] }
serde_json = "1.0.127"
