#!/usr/bin/env fish
# ------------------------- #
# Open a project using fzf. #
# ------------------------- #

zellij action rename-pane open-project
set selection (printf '%s\n' ~/Projects/* | xargs --delimiter '\n' --max-args 1 basename | fzf) || return
cd ~/Projects/$selection

# TabName: Split on `-` AND capitalize
for word in (string split - $selection)
    set tabname "$tabname"(string sub --length 1 -- $word | string upper)(string sub --start 2 -- $word)
end
zellij action rename-tab $tabname

if test -d .venv
    source .venv/bin/activate.fish
end
zellij action rename-pane hx
hx
