[package]
name = "record-reencoder"
version = "1.0.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
