#!/usr/bin/sh

printf 'Open images recursively? (y/N): '
read -r resp

if [ "${resp}" = "y" ]; then
  find . -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.gif' \) -print0 | \
    xargs --max-chars=2092210 --exit --no-run-if-empty --null vimiv -s shuffle true > /dev/null 2>&1 &
else
  vimiv -s shuffle true ./* > /dev/null 2>&1 &
fi
