#!/usr/bin/sh

printf 'Open images recursively? (y/N): '
read -r resp

if [ "${resp}" = "y" ]; then
  find . -type f -exec vimiv -s sort.shuffle true --command 'goto 1' '{}' '+' > /dev/null 2>&1 &
else
  vimiv -s sort.shuffle true --command 'goto 1' ./* > /dev/null 2>&1 &
fi
