#!/bin/bash
# Script used by nvim to show notifications when using make

set -eE

notify_success() {
  notify-send -t 15000 -a Neovim \
    -i /usr/share/icons/breeze-dark/status/64/dialog-positive.svg \
    'Job finished!' "make $* finished successfully!"
}

notify_fail() {
  notify-send -u critical -a Neovim \
    -i /usr/share/icons/breeze-dark/status/64/dialog-error.svg \
    'Job finished!' "make $* finished with errors..."
}

trap 'notify_fail $@' ERR

make "$@"
notify_success "$@"
