theme = "onedark_modified"

[editor]
color-modes = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
git-ignore = false
git-global = false
git-exclude = false

[editor.gutters.line-numbers]
min-width = 2

[editor.soft-wrap]
enable = true
