[terminal]
vt = 1

[default_session]
command = "tuigreet --user-menu --remember --asterisks --time --time-format '%Y-%m-%d %H:%M' --window-padding 1 --container-padding 2 --cmd fish"
user = "greeter"
