#!/usr/bin/fish
# Resize and convert an image to use it on Anki.

set --local selection -- $nnn
set --local fname (path change-extension '' $nnn)

if test (path extension $nnn) = '.webp'
    set selection -- $fname-original.webp
    mv -- $nnn $selection
end

magick $selection -strip -trim -resize '320x260>' -define webp:method=6 $fname.webp

# Preview
vimiv --log-level error $fname.webp
