#!/usr/bin/env fish
# -------------------------------- #
# Drag and drop current selection. #
# -------------------------------- #

source (status dirname)/.utils

nnn_get_selection DragDrop drag $argv[1] || return

if test (count $NNN_SELECTION) -eq 1
    nohup dragon-drop --and-exit $NNN_SELECTION &>/dev/null &
else
    nohup dragon-drop $NNN_SELECTION &>/dev/null &
end
