#!/usr/bin/fish

echo "[ffmpeg-trim] Going to trim selected video"
read --line --prompt-str 'From > ' from
read --line --prompt-str 'Until> ' until

set options
if test -n $from
    set --append options -ss $from
end
if test -n $until
    set --append options -to $until
end
if test -z "$options"
    return 0
end

echo '[ffmpeg-trim] Processing...'
ffmpeg -loglevel warning $options -i $nnn -codec copy -avoid_negative_ts make_zero -y trim-$nnn || return
touch --reference $nnn trim-$nnn

echo "[ffmpeg-trim] Before : $(du -h $nnn | cut -f 1)"
echo "[ffmpeg-trim] After  : $(du -h trim-$nnn | cut -f 1)"
mpv --really-quiet trim-$nnn

read --line --prompt-str 'Replace original? [y/N] ' replace
if string match --quiet --regex '^[Yy]$' $replace
    trash-put $nnn
    mv trim-$nnn $nnn
else
    rm --force -- trim-$nnn
end
