#!/usr/bin/env fish
# -------------------------------------------------- #
# Move files selected with mvi to current directory. #
# -------------------------------------------------- #

if test -s /tmp/mvi_selection
    while read --null selection
        mv $selection .
    end </tmp/mvi_selection
else
    echo '[MVIMOVE] No mvi selection' >&2
    return 1
end

rm --force /tmp/mvi_selection
