#!/usr/bin/fish

if test -s /tmp/mvi_selection
    while read --null selection
        mv $selection .
    end </tmp/mvi_selection
else
    echo 'No mvi selection' >&2
    return 1
end

rm --force /tmp/mvi_selection
