#!/usr/bin/env fish

switch (path extension $nnn)
    case '.fish'
        fish $nnn
    case '.gpg'
        gpg-open $nnn
    case '.rre'
        nohup nice record-reencoder $nnn &>~/.local/logs/ffmpeg-(date '+%s').log &
    case '*'
        xdg-open $nnn
end
