#!/usr/bin/fish

set find_options '(' -iname '*.jpg' -or -iname '*.jpeg' -or -iname '*.png' -or -iname '*.gif' -or -iname '*.webp' -or -iname '*.svg' -or -iname '*.bmp' ')'

if test -f $nnn
    if test (file $nnn) = "$nnn: ASCII text"
        # Text file with filenames in each line
        xargs --delimiter '\n' vimiv --log-level error -s sort.shuffle true --command 'goto 1' < $nnn &> /dev/null &
    else
        # Find pictures in current dir
        find . -maxdepth 1 -type f $find_options \
            -exec nohup vimiv --log-level critical -s sort.shuffle true --command 'goto 1' '{}' '+' &> /dev/null &
    end
else if test -d $nnn
    # Find pictures inside selected dir
    find $nnn -maxdepth 2 -type f -not -path '*/.*' $find_options \
        -exec nohup vimiv --log-level critical -s sort.shuffle true --command 'goto 1' '{}' '+' &> /dev/null &
end
